<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class ProfessionalsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('professionals')->insert([
            [
                'center_id'     => 1,
                'role_id'        => 1,
                'name'          => 'Admin',
                'surnames'      => 'Principal',
                'username'      => 'admin',
                'password'      => Hash::make('1234'),
                'phone_number'  => '600123456',
                'email_address' => 'admin@vallparadis.cat',
                'address'       => 'Carrer Major 123',
                'number_locker' => 12,
                'occupation'    => 'psicòleg',
                'clue_locker'   => 'A1B2C3',
                'link_status'   => 'Actiu',
                'status'   => 'active',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'center_id'     => 1,
                'role_id'        => 2,
                'name'          => 'Laura',
                'surnames'      => 'Pérez Gómez',
                'username'      => 'lperez',
                'password'      => Hash::make('1234'),
                'phone_number'  => '600654321',
                'email_address' => 'lperez@vallparadis.cat',
                'address'       => 'Av. Catalunya 45',
                'number_locker' => 8,
                'occupation'    => 'psicòleg',
                'clue_locker'   => 'D4E5F6',
                'link_status'   => 'Baixa',
                'status'   => 'inactive',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 3,
                'name' => 'Carlos',
                'surnames' => 'Ramírez Gómez',
                'username' => 'carlosrg',
                'password' => Hash::make('1234'),
                'phone_number' => '612345678',
                'email_address' => 'carlos.ramirez@example.com',
                'address' => 'Calle Mayor 12, Madrid',
                'number_locker' => 101,
                'occupation'    => 'fisioterapeuta',
                'clue_locker' => 'CL-82A',
                'link_status' => 'Actiu',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 4,
                'name' => 'María',
                'surnames' => 'Fernández López',
                'username' => 'mfernandez',
                'password' => Hash::make('1234'),
                'phone_number' => '611223344',
                'email_address' => 'maria.fernandez@example.com',
                'address' => 'Av. de la Libertad 8, Sevilla',
                'number_locker' => 102,
                'occupation'    => 'fisioterapeuta',
                'clue_locker' => 'CL-19B',
                'link_status' => 'Baixa',
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 4,
                'name' => 'Javier',
                'surnames' => 'Santos Díaz',
                'username' => 'jsantos',
                'password' => Hash::make('1234'),
                'phone_number' => '699887766',
                'email_address' => 'javier.santos@example.com',
                'address' => 'Calle Real 45, Valencia',
                'number_locker' => 103,
                'occupation'    => 'infermer',
                'clue_locker' => 'CL-77F',
                'link_status' => 'Actiu',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 4,
                'name' => 'Laura',
                'surnames' => 'García Ruiz',
                'username' => 'lauragr',
                'password' => Hash::make('1234'),
                'phone_number' => '622334455',
                'email_address' => 'laura.garcia@example.com',
                'address' => 'C/ del Sol 23, Málaga',
                'number_locker' => 104,
                'occupation'    => 'infermera',
                'clue_locker' => 'CL-13K',
                'link_status' => 'Actiu',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 4,
                'name' => 'Andrés',
                'surnames' => 'Martínez Ortega',
                'username' => 'andresmo',
                'password' => Hash::make('1234'),
                'phone_number' => '633112233',
                'email_address' => 'andres.martinez@example.com',
                'address' => 'Paseo del Río 10, Zaragoza',
                'number_locker' => 105,
                'occupation'    => 'Psicòleg',
                'clue_locker' => 'CL-29Q',
                'link_status' => 'Baixa',
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 4,
                'name' => 'Elena',
                'surnames' => 'Moreno Castro',
                'username' => 'elenamc',
                'password' => Hash::make('1234'),
                'phone_number' => '644556677',
                'email_address' => 'elena.moreno@example.com',
                'address' => 'Av. Andalucía 55, Granada',
                'number_locker' => 106,
                'occupation'    => 'infermera',
                'clue_locker' => 'CL-05Z',
                'link_status' => 'Actiu',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 4,
                'name' => 'Raúl',
                'surnames' => 'Pérez Jiménez',
                'username' => 'raulpj',
                'password' => Hash::make('1234'),
                'phone_number' => '655667788',
                'email_address' => 'raul.perez@example.com',
                'address' => 'C/ de las Flores 5, Bilbao',
                'number_locker' => 107,
                'occupation'    => 'infermera',
                'clue_locker' => 'CL-84N',
                'link_status' => 'Actiu',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 4,
                'name' => 'Lucía',
                'surnames' => 'Gómez Sánchez',
                'username' => 'luciags',
                'password' => Hash::make('1234'),
                'phone_number' => '699112233',
                'email_address' => 'lucia.gomez@example.com',
                'address' => 'Plaza Nueva 3, León',
                'number_locker' => 108,
                'occupation'    => 'Psicòlega',
                'clue_locker' => 'CL-55T',
                'link_status' => 'Baixa',
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 4,
                'name' => 'David',
                'surnames' => 'López Torres',
                'username' => 'davidlt',
                'password' => Hash::make('1234'),
                'phone_number' => '611998877',
                'email_address' => 'david.lopez@example.com',
                'address' => 'C/ Castilla 40, Burgos',
                'number_locker' => 109,
                'occupation'    => 'Logopeda',
                'clue_locker' => 'CL-71Y',
                'link_status' => 'Actiu',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'center_id' => 1,
                'role_id'    => 4,
                'name' => 'Patricia',
                'surnames' => 'Navarro Vega',
                'username' => 'patricianv',
                'password' => Hash::make('1234'),
                'phone_number' => '677334455',
                'email_address' => 'patricia.navarro@example.com',
                'address' => 'Av. Galicia 9, Vigo',
                'number_locker' => 110,
                'occupation'    => 'Logopeda',
                'clue_locker' => 'CL-62J',
                'link_status' => 'Actiu',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
